### ISSUE TITLE
Problem with the Enrichr consensus Appyter - Error in GMT file format

### ISSUE THREAD

**Issue by AviMaayan** [MaayanLab/appyter-catalog#521]
This is the appyter instance:
https://appyters.maayanlab.cloud/Enrichr_Consensus_Terms/40d4e1b38f0636b9b71e56a9fb2d03dcd3c5985d/

![image](https://user-images.githubusercontent.com/12749033/107734562-b40f6200-6ccb-11eb-9af0-5e583f12283c.png)

This is the input file:
[Phosphoproteomics_sets_v1_02-02-21-down.gmt.txt](https://github.com/MaayanLab/appyter-catalog/files/5969870/Phosphoproteomics_sets_v1_02-02-21-down.gmt.txt)

Selected several libraries (ChEA, KEA, GO BP, MGI).

This is where the GMT file is from: https://maayanlab.cloud/covid19/static/Phosphoproteomics_sets_v1_02-02-21.gmt

**Comment by jeevangelista** [comment]
@AviMaayan This happens when the terms are not separated to their respective gene sets with two tabs: '\t\t' I fixed the input and got this results: https://appyters.maayanlab.cloud/Enrichr_Consensus_Terms/4f5f4b04437002ba3817ed3293c315a17d09ab02/

I'm also pushing a fix that should handle this case

**Comment by AviMaayan** [comment]
@jeevangelista this looks great! Can you produce a report for the up regulated phospho-proteomics sets?

**Comment by jeevangelista** [comment]
Fixed: 52d7648cd5fe8c082a887b9ac2c506741bd23a36
