### ISSUE TITLE
MemoryError: Unable to allocate array with shape (50760, 26609) and data type float64

### ISSUE THREAD

**Issue by sarasaezALS** [MaayanLab/appyter-catalog#546]
Hi everyone,
I am trying to run Drugmonizome-ML using Appyter (using the example list of drugs) but I get the following error:
MemoryError: Unable to allocate array with shape (50760, 26609) and data type float64.
Is there anything i can do?

**Comment by u8sand** [comment]
@sarasaezALS Thank you for your report. It would really help to have the persistent link to the instance which failed in this way (for example, <https://appyters.maayanlab.cloud/Drugmonizome_ML/c948efe4623b3f3eeeda84ee7cdb4bd8279a80b9/> is the example using all the defaults) so we can check that our examples don't involve excessive amounts of data to exhaust our platform's memory constraints.

We have a set amount of memory for serving appyters because of cost constraints and unfortunately cannot dedicate more than we already have allocated. It should be possible to run the analysis with your own resources with the `Run Locally` button which will allow you to execute the notebook in a docker container.

**Comment by sarasaezALS** [comment]
Thanks @u8sand!
This is the link
https://appyters.maayanlab.cloud/Drugmonizome_ML/440f6ee2d75c5a78cd9691bb7d383288111fac34/#select-input-datasets-and-target-classes
I will try to run it locally then

**Comment by AviMaayan** [comment]
Hi @sarasaezALS the problem is with these datasets for attribute selection: 
![image](https://user-images.githubusercontent.com/12749033/110699575-035a8c80-81bd-11eb-8df9-a954a279dba8.png)
If you select other datasets, it should work... but these large attribute datasets are the best for making predictions, but it only works locally or in other clouds because of the memory requirement...

**Comment by sarasaezALS** [comment]
Thanks @AviMaayan!
I will do it locally!
